version: '3.1'

services:
  iq2-nginx:
    container_name: iq2-nginx
    hostname: iq2-nginx
    image: 863067839821.dkr.ecr.ap-northeast-2.amazonaws.com/iq2-nginx:latest
#    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      TZ: "Asia/Seoul"
      IQ2_NGINX_MGR_PORT: 20004
      
      IQ2_MASTER_CLUSTER_INFO: "Cluster Master IP:Port (comma separated)"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nginx-logs:/iq2/iq2-nginx/logs:rw
      - nginx-mgr-logs:/iq2/iq2-nginx/mgr/logs:rw
    ports:
      - "80-90:80-90"
      - "20004:20004"

volumes:
    nginx-logs:
    nginx-mgr-logs: