version: '3.1'

services:
  iq2-edge:
    container_name: iq2-edge
    hostname: iq2-edge
    image: 863067839821.dkr.ecr.ap-northeast-2.amazonaws.com/iq2-edge:latest
#    restart: always
    cap_add:
      - SYS_PTRACE
    environment:      
      IQ2_EDGE_NAME: "EDGE Name (Ex. APINF-EDGE-1)"
      IQ2_NGINX_MGR_PORT: 20004      
      IQ2_MASTER_CLUSTER_INFO: "Cluster Master IP:Port (comma separated)"
    volumes:
      - nginx-mgr-conf:/iq2/edge/iq2-nginx-mgr/conf:rw
      - nginx-conf:/iq2/edge/iq2-nginx-mgr/nginx-conf:rw
      - nginx-mgr-logs:/iq2/edge/iq2-nginx-mgr/logs:rw
      - nginx-logs:/iq2/edge/iq2-nginx/logs:rw
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"

volumes:
    nginx-mgr-conf:
    nginx-conf:
    nginx-mgr-logs:
    nginx-logs:
