version: '3.1'

services:
  iq2-nginx:
    container_name: iq2-nginx
    hostname: iq2-nginx
    image: 863067839821.dkr.ecr.ap-northeast-2.amazonaws.com/iq2-nginx:latest
#    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      IQ2_NGINX_MGR_PORT: 20004
      IQ2_MASTER_API_HOST: "IQ2_CONTROLLER_IP"
      IQ2_MASTER_API_PORT: 20000
      IQ2_DATASURFER_COLLECTOR_HOST: "IQ2_CONTROLLER_IP"
      IQ2_DATASURFER_COLLECTOR_PORT: 20002
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80-90:80-90"
      - "20004:20004"
