version: '3.1'

services:
  balancer-nginx:
    container_name: balancer-nginx
    hostname: balancer-nginx
    image: 863067839821.dkr.ecr.ap-northeast-2.amazonaws.com/balancer-nginx:latest
#    restart: always
    cap_add:
      - SYS_PTRACE
    environment:
      BALANCER_ROUTER_API_PORT: 40000
      BALANCER_MASTER_API_HOST: "BALANCER_CONTROLLER_IP"
      BALANCER_MASTER_API_PORT: 42000
      BALANCER_DATASURFER_COLLECTOR_HOST: "BALANCER_CONTROLLER_IP"
      BALANCER_DATASURFER_COLLECTOR_PORT: 5885
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "80-90:80-90"
      - "40000:40000"